import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar";
import YoutubePlayer from "@/components/YoutubePlayer";
import Playlist from "@/components/playlist";
import SideBar from "@/components/SideBar";
import { SearchProvider } from '@/components/contexts/searchContext';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <SearchProvider>
        <Navbar />
        <div className="container px-6 pt-5">
          <div className="flex h-full gap-10">
            <div className="flex w-1/12 bg-secondary rounded-3xl h-min p-4">
              <SideBar />
            </div>
            {children}
            <div className="flex-1 bg-secondary rounded-3xl p-4 h-min"> 
              <YoutubePlayer videoId="enidMo5izlE" />
            </div>
          </div>
        </div>
        </SearchProvider>
      </body>
    </html>
  );
}
